### ISSUE TITLE
Return an EmissivityProfile from InvertRadiation

### ISSUE THREAD

**Issue by elitherl** [indica-mcf/Indica#303]
When `InvertRadiation` fits a symmetric emissivity profile and asymmetry parameter, return the `EmissivityProfile` class constructed from these rather than evaluating that on an R, z grid. Would offer more flexibility to using the emissivity, and would only be a trivial change to code using `InvertRadiation` to keep the same behaviour

**Comment by elitherl** [comment]
@marcosertoli would this change cause any issues for you?

I'm thinking of just removing  this section from `__call__` and returning the `EmissivityProfile` directly:

```python
estimate = EmissivityProfile(
    symmetric_emissivity, asymmetry_parameter, flux_coords
)
trivial = TrivialTransform()
emissivity = estimate(trivial, R, z, times)
emissivity.attrs["datatype"] = ("emissivity", self.datatype)
emissivity.attrs["emissivity_model"] = estimate
emissivity.name = self.datatype + "_emissivity"
```

So then calling `estimate` could be moved to any code using this that still wants an R,z profile, but it's not forced if not need (i.e. I'd find it very useful to get the emissivity back in rho space at the moment)

**Comment by marcosertoli** [comment]
No, Evie, won't affect me at all.

I'm not using the master version and have drafted a simplified version of it in the st40 branch.
