### ISSUE TITLE
ST40 Reader Revisions are always BEST

### ISSUE THREAD

**Issue by michael-gemmell** [indica-mcf/Indica#336]
https://github.com/indica-mcf/Indica/blob/b79b1f17e93f11ecef18d8dd6c96687901606236/indica/readers/st40reader.py#L88C4-L103C76

The best revision is always used regardless of what is given to ST40Reader

**Comment by michael-gemmell** [comment]
Missed that was fixed on the main branch

**Comment by marcosertoli** [comment]
This is already fixed in the main branch.
